function parseCsv(value) {
  return (value || '')
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function buildIssueBody({
  mention,
  branches,
  daysInactive,
  watcherMentions,
  authorInfo,
}) {
  const totalOpenPrs = branches.reduce((sum, branch) => sum + (branch.openPrs?.length ?? 0), 0);
  const branchesWithOpenPr = branches.filter((branch) => (branch.openPrs?.length ?? 0) > 0).length;
  const tableRows = branches
    .map((branch) => {
      const prCell = branch.openPrs && branch.openPrs.length > 0
        ? branch.openPrs.map((pr) => `[#${pr.number}](${pr.url})`).join(', ')
        : 'None';
      return `| \`${branch.name}\` | \`${branch.sha}\` | ${branch.lastCommitISO} | ${branch.daysSince} days | ${prCell} |`;
    })
    .join('\n');

  const authorSection = authorInfo
    ? `> **ℹ️ Original author:** @${authorInfo.handle} (${authorInfo.name} / ${authorInfo.email}) — no longer an active collaborator.\n`
    : '';

  return [
    '## 🌿 Stale Feature Branch — Action Required',
    '',
    `Hi ${mention},`,
    '',
    'The following feature branch(es) associated with your account have had **no commits',
    `for ${daysInactive}+ days** and need attention:`,
    '',
    '| Branch | Last Commit SHA | Last Commit Date | Inactive For | Open PR(s) |',
    '|--------|-----------------|------------------|--------------|------------|',
    tableRows,
    '',
    '### Pull Request Status',
    '',
    `- Open PRs linked to these stale branches: **${totalOpenPrs}**`,
    `- Branches with open PRs: **${branchesWithOpenPr}/${branches.length}**`,
    '',
    ...(authorInfo ? [authorSection, ''] : []),
    '### Please take **one** of these actions for each branch:',
    '',
    '| Action | When to use |',
    '|--------|-------------|',
    '| 🔨 **Push new commits** | Work is still in progress |',
    '| 🔀 **Open a Pull Request** | Work is ready for review |',
    '| 🗑️ **Delete the branch** | Work is abandoned or merged elsewhere |',
    '',
    '> ⚠️ Stale branches add clutter and make navigation harder for the team.',
    '> Please **close this issue** once you have taken action on all listed branches.',
    '',
    '---',
    `📢 **CC for visibility:** ${watcherMentions}`,
    '',
    '---',
    `_Auto-generated by the Stale Branch Notifier action · ${new Date().toISOString().split('T')[0]}_`,
  ].join('\n');
}

async function ensureLabel({ github, context }) {
  try {
    await github.rest.issues.getLabel({
      owner: context.repo.owner,
      repo: context.repo.repo,
      name: 'stale-branch',
    });
    console.log("Label 'stale-branch' already exists.");
  } catch (error) {
    if (error.status !== 404) {
      throw error;
    }

    await github.rest.issues.createLabel({
      owner: context.repo.owner,
      repo: context.repo.repo,
      name: 'stale-branch',
      color: 'e4e669',
      description: 'Branch has been inactive for 15+ days — action required',
    });
    console.log("Created label 'stale-branch'.");
  }
}

async function getOpenPrsForBranch({ github, context, branchName }) {
  const { data } = await github.rest.pulls.list({
    owner: context.repo.owner,
    repo: context.repo.repo,
    state: 'open',
    head: `${context.repo.owner}:${branchName}`,
    per_page: 10,
  });

  return data.map((pr) => ({
    number: pr.number,
    url: pr.html_url,
  }));
}

async function getStaleBranches({ github, context, cutoff, excludedBranches }) {
  const allBranches = await github.paginate(github.rest.repos.listBranches, {
    owner: context.repo.owner,
    repo: context.repo.repo,
    per_page: 100,
  });

  console.log(`Total branches to scan: ${allBranches.length}`);

  const staleBranches = [];
  for (const branch of allBranches) {
    if (excludedBranches.has(branch.name)) {
      console.log(`↪ Skipping excluded branch: ${branch.name}`);
      continue;
    }

    const { data: commitData } = await github.rest.repos.getCommit({
      owner: context.repo.owner,
      repo: context.repo.repo,
      ref: branch.commit.sha,
    });

    const lastCommitDate = new Date(commitData.commit.author.date);
    if (lastCommitDate >= cutoff) {
      continue;
    }

    const daysSince = Math.floor((Date.now() - lastCommitDate.getTime()) / 86400000);
    staleBranches.push({
      name: branch.name,
      sha: branch.commit.sha.slice(0, 7),
      lastCommitISO: lastCommitDate.toISOString().split('T')[0],
      daysSince,
      authorLogin: commitData.author?.login ?? null,
      authorName: commitData.commit.author.name,
      authorEmail: commitData.commit.author.email,
    });
  }

  return staleBranches;
}

async function resolveAssignableLogin({ github, context, dryRun, login, name, email }) {
  let validLogin = login;
  let authorInfo = null;

  if (dryRun || !login) {
    return { validLogin, authorInfo };
  }

  try {
    const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
      owner: context.repo.owner,
      repo: context.repo.repo,
      username: login,
    });

    if (['admin', 'maintain', 'write', 'pull'].includes(data.permission)) {
      console.log(`✓ User @${login} is a collaborator with "${data.permission}" access — will assign.`);
      return { validLogin, authorInfo };
    }

    console.warn(`⚠️ User @${login} returned permission "${data.permission}" and is not assignable. Will assign to watchers and mention in issue.`);
  } catch (error) {
    if (error.status === 404 && login === context.repo.owner) {
      console.log(`✓ User @${login} is the repo owner (implicit admin) — will assign.`);
      return { validLogin, authorInfo };
    }

    if (error.status !== 404) {
      throw error;
    }

    console.warn(`⚠️ User @${login} is not a valid collaborator. Will assign to watchers and mention in issue.`);
  }

  validLogin = null;
  authorInfo = { handle: login, name, email };
  return { validLogin, authorInfo };
}

async function createOrUpdateIssue({
  github,
  context,
  dryRun,
  displayName,
  mention,
  branches,
  daysInactive,
  watcherMentions,
  validLogin,
  authorInfo,
  watchers,
  openStaleIssues,
}) {
  const issueTitle = `[Stale Branch] Action needed: ${branches.length} inactive branch${branches.length > 1 ? 'es' : ''} — ${displayName}`;
  const assigneesToUse = validLogin ? [validLogin] : watchers;
  const issueBody = buildIssueBody({
    mention,
    branches,
    daysInactive,
    watcherMentions,
    authorInfo,
  });

  if (dryRun) {
    console.log(`[DRY RUN] Would create/update issue for "${displayName}" with ${branches.length} stale branch(es).`);
    return { touchedIssue: false };
  }

  const existing = openStaleIssues.find((issue) => issue.title.startsWith('[Stale Branch]') && issue.title.includes(displayName));

  if (existing) {
    try {
      await github.rest.issues.update({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: existing.number,
        title: issueTitle,
        body: issueBody,
        assignees: assigneesToUse,
      });
    } catch (error) {
      console.warn(`⚠️ Failed to update assignees for issue #${existing.number}: ${error.message}. Updating body only.`);
      await github.rest.issues.update({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: existing.number,
        title: issueTitle,
        body: issueBody,
      });
    }

    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: existing.number,
      body: `🔄 _Refreshed on ${new Date().toISOString().split('T')[0]} — ${branches.length} stale branch(es) still inactive._`,
    });
    console.log(`✓ Updated issue #${existing.number} for "${displayName}".`);
    return { touchedIssue: true };
  }

  let createdIssue;
  try {
    createdIssue = await github.rest.issues.create({
      owner: context.repo.owner,
      repo: context.repo.repo,
      title: issueTitle,
      body: issueBody,
      labels: ['stale-branch'],
      assignees: assigneesToUse,
    });
  } catch (error) {
    console.warn(`⚠️ Failed to create issue with assignees: ${error.message}. Creating without assignees.`);
    createdIssue = await github.rest.issues.create({
      owner: context.repo.owner,
      repo: context.repo.repo,
      title: issueTitle,
      body: issueBody,
      labels: ['stale-branch'],
    });

    if (assigneesToUse.length > 0) {
      await github.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: createdIssue.data.number,
        body: `⚠️ **Assignee note:** This issue was intended to be assigned to ${validLogin ? `@${validLogin}` : `[${assigneesToUse.join(', ')}]`}, but the assignment failed. Please review and assign manually if needed.`,
      });
    }
  }

  console.log(`✓ Created issue #${createdIssue.data.number} for "${displayName}".`);
  return { touchedIssue: true };
}

async function reconcileIssues({ github, context, dryRun, currentDisplayNames, openStaleIssues }) {
  let autoClosedCount = 0;

  for (const issue of openStaleIssues) {
    if (!issue.title.startsWith('[Stale Branch] Action needed:')) {
      continue;
    }

    const match = issue.title.match(/^\[Stale Branch\] Action needed: .* — (.+)$/);
    if (!match) {
      continue;
    }

    const issueDisplayName = match[1].trim();
    if (currentDisplayNames.has(issueDisplayName)) {
      continue;
    }

    if (dryRun) {
      console.log(`[DRY RUN] Would auto-close issue #${issue.number} (${issue.title})`);
      continue;
    }

    const closeComment = [
      '✅ **Auto-closed by Stale Branch Notifier**',
      '',
      'No actionable stale branches remain for this issue owner in the current scan.',
      '',
      'This usually means all previously listed branches were either:',
      '- deleted',
      '- excluded by policy (`STALE_BRANCH_NOTIFIER_EXCLUDED_BRANCHES` or default branch guard), or',
      '- no longer stale (new activity detected).',
      '',
      'If needed, remove branch exclusions and rerun the action.',
    ].join('\n');

    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: closeComment,
    });

    await github.rest.issues.update({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      state: 'closed',
      state_reason: 'completed',
    });

    autoClosedCount += 1;
    console.log(`✓ Auto-closed stale issue #${issue.number} (${issueDisplayName}) — no actionable stale branches remain.`);
  }

  return autoClosedCount;
}

module.exports = async function runNotifier({ github, context, core, inputs, repoVars = {} }) {
  await ensureLabel({ github, context });

  const rawDaysInactive = repoVars.daysInactive || inputs.daysInactive || '15';
  let daysInactive = parseInt(rawDaysInactive, 10);
  if (!Number.isFinite(daysInactive) || daysInactive <= 0) {
    console.warn(`⚠️ Invalid days threshold "${rawDaysInactive}". Falling back to 15 days.`);
    daysInactive = 15;
  }

  const dryRun = String(inputs.dryRun).toLowerCase() === 'true';
  const defaultBranch = context.payload.repository?.default_branch || 'main';
  const watchers = parseCsv(repoVars.watchers || inputs.watchers);
  const excludedBranches = new Set([defaultBranch, ...parseCsv(repoVars.excludedBranches || inputs.excludedBranches)]);
  const watcherMentions = watchers.length > 0 ? watchers.map((watcher) => `@${watcher}`).join(' ') : '(no watchers configured)';

  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - daysInactive);

  console.log(`Config → days_inactive=${daysInactive}, dry_run=${dryRun}`);
  console.log(repoVars.daysInactive ? `✓ Using days threshold from repo variable: ${daysInactive}` : `✓ Using days threshold from action input/default: ${daysInactive}`);
  if (watchers.length > 0) {
    console.log(`${repoVars.watchers ? '✓ Using watchers from repo variable' : '✓ Using watchers from action input'}: [${watchers.join(', ')}]`);
  } else {
    console.log('⚠️ No watchers configured.');
  }
  console.log(`Default branch (always excluded): ${defaultBranch}`);
  console.log(`Excluded branches: [${Array.from(excludedBranches).join(', ')}]`);
  console.log(`Stale cutoff date: ${cutoff.toISOString().split('T')[0]}`);

  const staleBranches = await getStaleBranches({ github, context, cutoff, excludedBranches });
  console.log(`Stale branches (inactive ${daysInactive}+ days): ${staleBranches.length}`);
  if (staleBranches.length === 0) {
    console.log('✅ No stale branches detected in this run. Will reconcile open stale issues.');
  }

  const byAuthor = {};
  for (const branch of staleBranches) {
    const key = branch.authorLogin ?? branch.authorName;
    if (!byAuthor[key]) {
      byAuthor[key] = {
        login: branch.authorLogin,
        name: branch.authorName,
        email: branch.authorEmail,
        branches: [],
      };
    }
    byAuthor[key].branches.push(branch);
  }

  const currentDisplayNames = new Set(Object.values(byAuthor).map((author) => author.login ?? author.name));
  const openStaleIssues = await github.paginate(github.rest.issues.listForRepo, {
    owner: context.repo.owner,
    repo: context.repo.repo,
    state: 'open',
    labels: 'stale-branch',
    per_page: 100,
  });

  let touchedIssuesCount = 0;
  for (const [key, author] of Object.entries(byAuthor)) {
    const displayName = author.login ?? author.name;
    const mention = author.login ? `@${author.login}` : `**${author.name}**`;

    for (const branch of author.branches) {
      branch.openPrs = await getOpenPrsForBranch({ github, context, branchName: branch.name });
    }

    try {
      const { validLogin, authorInfo } = await resolveAssignableLogin({
        github,
        context,
        dryRun,
        login: author.login,
        name: author.name,
        email: author.email,
      });

      const { touchedIssue } = await createOrUpdateIssue({
        github,
        context,
        dryRun,
        displayName,
        mention,
        branches: author.branches,
        daysInactive,
        watcherMentions,
        validLogin,
        authorInfo,
        watchers,
        openStaleIssues,
      });

      if (touchedIssue) {
        touchedIssuesCount += 1;
      }
    } catch (error) {
      console.error(`❌ Error processing author "${key}": ${error.message}`);
    }
  }

  const autoClosedCount = await reconcileIssues({
    github,
    context,
    dryRun,
    currentDisplayNames,
    openStaleIssues,
  });

  core.setOutput('stale_count', String(staleBranches.length));
  core.setOutput('issues_count', String(touchedIssuesCount));
  core.setOutput('auto_closed_count', String(autoClosedCount));
  console.log(`Done. Processed ${Object.keys(byAuthor).length} author(s), ${staleBranches.length} stale branch(es), auto-closed ${autoClosedCount} issue(s).`);
};