function parseCsv(value) {
  return (value || '')
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function buildIssueBody({
  mention,
  branches,
  daysInactive,
  defaultBranch,
  watcherMentions,
  authorInfo,
}) {
  const totalOpenPrs = branches.reduce((sum, branch) => sum + (branch.openPrs?.length ?? 0), 0);
  const branchesWithOpenPr = branches.filter((branch) => (branch.openPrs?.length ?? 0) > 0).length;
  const tableRows = branches
    .map((branch) => {
      const prCell = branch.openPrs && branch.openPrs.length > 0
        ? branch.openPrs.map((pr) => `[#${pr.number}](${pr.url})`).join(', ')
        : 'None';
      return `| \`${branch.name}\` | \`${branch.sha}\` | ${branch.lastCommitISO} | ${branch.daysSince} days | ${prCell} |`;
    })
    .join('\n');

  const diffRows = branches
    .map((branch) => {
      if (!branch.diff) {
        return `| \`${branch.name}\` | — | — | — | — |`;
      }
      const { aheadBy, behindBy, changedFiles, additions, deletions, compareUrl } = branch.diff;
      const filesCell = changedFiles !== null ? `${changedFiles} (+${additions}/-${deletions})` : '—';
      const diffLink = compareUrl ? `[Compare](${compareUrl})` : '—';
      return `| \`${branch.name}\` | ${aheadBy} | ${behindBy} | ${filesCell} | ${diffLink} |`;
    })
    .join('\n');

  const authorSection = authorInfo
    ? `> **ℹ️ Original author:** @${authorInfo.handle} (${authorInfo.name} / ${authorInfo.email}) — no longer an active collaborator.\n`
    : '';

  return [
    '## 🌿 Stale Feature Branch — Action Required',
    '',
    `Hi ${mention},`,
    '',
    'The following feature branch(es) associated with your account have had **no commits',
    `for ${daysInactive}+ days** and need attention:`,
    '',
    '| Branch | Last Commit SHA | Last Commit Date | Inactive For | Open PR(s) |',
    '|--------|-----------------|------------------|--------------|------------|',
    tableRows,
    '',
    '### Pull Request Status',
    '',
    `- Open PRs linked to these stale branches: **${totalOpenPrs}**`,
    `- Branches with open PRs: **${branchesWithOpenPr}/${branches.length}**`,
    '',
    `### Diff Summary (vs \`${defaultBranch}\`)`,
    '',
    `| Branch | Commits Ahead | Commits Behind | Files Changed | Full Diff |`,
    `|--------|--------------|----------------|---------------|-----------|`,
    diffRows,
    '',
    ...(authorInfo ? [authorSection, ''] : []),
    '### Please take **one** of these actions for each branch:',
    '',
    '| Action | When to use |',
    '|--------|-------------|',
    '| 🔨 **Push new commits** | Work is still in progress |',
    '| 🔀 **Open a Pull Request** | Work is ready for review |',
    '| 🗑️ **Delete the branch** | Work is abandoned or merged elsewhere |',
    '',
    '> ⚠️ Stale branches add clutter and make navigation harder for the team.',
    '> Please **close this issue** once you have taken action on all listed branches.',
    '',
    '---',
    `📢 **CC for visibility:** ${watcherMentions}`,
    '',
    '---',
    `_Auto-generated by the Stale Branch Notifier action · ${new Date().toISOString().split('T')[0]}_`,
  ].join('\n');
}

async function ensureLabel({ github, context }) {
  try {
    await github.rest.issues.getLabel({
      owner: context.repo.owner,
      repo: context.repo.repo,
      name: 'stale-branch',
    });
    console.log("Label 'stale-branch' already exists.");
  } catch (error) {
    if (error.status !== 404) {
      throw error;
    }

    await github.rest.issues.createLabel({
      owner: context.repo.owner,
      repo: context.repo.repo,
      name: 'stale-branch',
      color: 'e4e669',
      description: 'Branch has been inactive for 15+ days — action required',
    });
    console.log("Created label 'stale-branch'.");
  }
}

async function getOpenPrsForBranch({ github, context, branchName }) {
  const { data } = await github.rest.pulls.list({
    owner: context.repo.owner,
    repo: context.repo.repo,
    state: 'open',
    head: `${context.repo.owner}:${branchName}`,
    per_page: 10,
  });

  return data.map((pr) => ({
    number: pr.number,
    url: pr.html_url,
  }));
}

async function getStaleBranches({ github, context, cutoff, excludedBranches, defaultBranch }) {
  const allBranches = await github.paginate(github.rest.repos.listBranches, {
    owner: context.repo.owner,
    repo: context.repo.repo,
    per_page: 100,
  });

  console.log(`Total branches to scan: ${allBranches.length}`);

  const staleBranches = [];
  for (const branch of allBranches) {
    if (excludedBranches.has(branch.name)) {
      console.log(`↪ Skipping excluded branch: ${branch.name}`);
      continue;
    }

    const { data: commitData } = await github.rest.repos.getCommit({
      owner: context.repo.owner,
      repo: context.repo.repo,
      ref: branch.commit.sha,
    });

    const lastCommitDate = new Date(commitData.commit.author.date);
    if (lastCommitDate >= cutoff) {
      continue;
    }

    const daysSince = Math.floor((Date.now() - lastCommitDate.getTime()) / 86400000);

    // Fetch diff summary vs the default branch
    let diff = null;
    try {
      const { data: compareData } = await github.rest.repos.compareCommits({
        owner: context.repo.owner,
        repo: context.repo.repo,
        base: defaultBranch,
        head: branch.name,
      });
      const files = compareData.files || [];
      diff = {
        aheadBy: compareData.ahead_by,
        behindBy: compareData.behind_by,
        changedFiles: files.length,
        additions: files.reduce((sum, f) => sum + f.additions, 0),
        deletions: files.reduce((sum, f) => sum + f.deletions, 0),
        compareUrl: compareData.html_url,
      };
    } catch (err) {
      console.warn(`⚠️ Could not fetch diff for "${branch.name}": ${err.message}`);
    }

    staleBranches.push({
      name: branch.name,
      sha: branch.commit.sha.slice(0, 7),
      lastCommitISO: lastCommitDate.toISOString().split('T')[0],
      daysSince,
      authorLogin: commitData.author?.login ?? null,
      authorName: commitData.commit.author.name,
      authorEmail: commitData.commit.author.email,
      diff,
    });
  }

  return staleBranches;
}

async function resolveAssignableLogin({ github, context, dryRun, login, name, email }) {
  let validLogin = login;
  let authorInfo = null;

  if (dryRun || !login) {
    return { validLogin, authorInfo };
  }

  try {
    const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
      owner: context.repo.owner,
      repo: context.repo.repo,
      username: login,
    });

    if (['admin', 'maintain', 'write', 'pull'].includes(data.permission)) {
      console.log(`✓ User @${login} is a collaborator with "${data.permission}" access — will assign.`);
      return { validLogin, authorInfo };
    }

    console.warn(`⚠️ User @${login} returned permission "${data.permission}" and is not assignable. Will assign to watchers and mention in issue.`);
  } catch (error) {
    if (error.status === 404 && login === context.repo.owner) {
      console.log(`✓ User @${login} is the repo owner (implicit admin) — will assign.`);
      return { validLogin, authorInfo };
    }

    if (error.status !== 404) {
      throw error;
    }

    console.warn(`⚠️ User @${login} is not a valid collaborator. Will assign to watchers and mention in issue.`);
  }

  validLogin = null;
  authorInfo = { handle: login, name, email };
  return { validLogin, authorInfo };
}

async function createOrUpdateIssue({
  github,
  context,
  dryRun,
  displayName,
  mention,
  branches,
  daysInactive,
  defaultBranch,
  watcherMentions,
  validLogin,
  authorInfo,
  watchers,
  openStaleIssues,
}) {
  const issueTitle = `[Stale Branch] Action needed: ${branches.length} inactive branch${branches.length > 1 ? 'es' : ''} — ${displayName}`;
  const assigneesToUse = validLogin ? [validLogin] : watchers;
  const issueBody = buildIssueBody({
    mention,
    branches,
    daysInactive,
    defaultBranch,
    watcherMentions,
    authorInfo,
  });

  if (dryRun) {
    console.log(`[DRY RUN] Would create/update issue for "${displayName}" with ${branches.length} stale branch(es).`);
    return { touchedIssue: false };
  }

  const existing = openStaleIssues.find((issue) => issue.title.startsWith('[Stale Branch]') && issue.title.includes(displayName));

  if (existing) {
    try {
      await github.rest.issues.update({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: existing.number,
        title: issueTitle,
        body: issueBody,
        assignees: assigneesToUse,
      });
    } catch (error) {
      console.warn(`⚠️ Failed to update assignees for issue #${existing.number}: ${error.message}. Updating body only.`);
      await github.rest.issues.update({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: existing.number,
        title: issueTitle,
        body: issueBody,
      });
    }

    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: existing.number,
      body: `🔄 _Refreshed on ${new Date().toISOString().split('T')[0]} — ${branches.length} stale branch(es) still inactive._`,
    });
    console.log(`✓ Updated issue #${existing.number} for "${displayName}".`);
    return { touchedIssue: true };
  }

  let createdIssue;
  try {
    createdIssue = await github.rest.issues.create({
      owner: context.repo.owner,
      repo: context.repo.repo,
      title: issueTitle,
      body: issueBody,
      labels: ['stale-branch'],
      assignees: assigneesToUse,
    });
  } catch (error) {
    console.warn(`⚠️ Failed to create issue with assignees: ${error.message}. Creating without assignees.`);
    createdIssue = await github.rest.issues.create({
      owner: context.repo.owner,
      repo: context.repo.repo,
      title: issueTitle,
      body: issueBody,
      labels: ['stale-branch'],
    });

    if (assigneesToUse.length > 0) {
      await github.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: createdIssue.data.number,
        body: `⚠️ **Assignee note:** This issue was intended to be assigned to ${validLogin ? `@${validLogin}` : `[${assigneesToUse.join(', ')}]`}, but the assignment failed. Please review and assign manually if needed.`,
      });
    }
  }

  console.log(`✓ Created issue #${createdIssue.data.number} for "${displayName}".`);
  return { touchedIssue: true };
}

function extractBranchesFromIssueBody(body) {
  const matches = [...(body || '').matchAll(/^\| `([^`]+)` \| `[0-9a-f]{7}`/gm)];
  return matches.map((m) => m[1]);
}

async function executeDeleteCommand({ github, context, issue, commenter, branchName, defaultBranch, excludedBranches }) {
  const issueBranches = extractBranchesFromIssueBody(issue.body);

  // Branch must be listed in this issue — prevents deleting unrelated branches
  if (!issueBranches.includes(branchName)) {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: `⛔ @${commenter} — \`${branchName}\` is not listed in this issue. You can only delete branches that appear in the table above.`,
    });
    console.warn(`⚠️ Branch "${branchName}" is not in issue #${issue.number} — rejected.`);
    return;
  }

  // Policy-protected branch check
  if (excludedBranches.has(branchName)) {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: `🛡️ **Delete blocked by policy** for \`${branchName}\`\n\nThis branch is in the protected exclude list or is the default branch (\`${defaultBranch}\`).`,
    });
    console.warn(`⚠️ Branch "${branchName}" is policy-protected — rejected.`);
    return;
  }

  // Verify branch exists
  try {
    await github.rest.repos.getBranch({
      owner: context.repo.owner,
      repo: context.repo.repo,
      branch: branchName,
    });
  } catch (error) {
    if (error.status === 404) {
      await github.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: issue.number,
        body: `❌ @${commenter} — \`${branchName}\` not found — it may have already been deleted.`,
      });
      return;
    }
    throw error;
  }

  // Block deletion if branch has open PRs
  const { data: openPrs } = await github.rest.pulls.list({
    owner: context.repo.owner,
    repo: context.repo.repo,
    state: 'open',
    head: `${context.repo.owner}:${branchName}`,
    per_page: 10,
  });

  if (openPrs.length > 0) {
    const prLinks = openPrs.map((pr) => `[#${pr.number}](${pr.html_url})`).join(', ');
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: `⚠️ **Cannot delete** \`${branchName}\` — it has open pull request(s): ${prLinks}\n\nPlease close or merge the PR(s) first.`,
    });
    console.warn(`⚠️ Branch "${branchName}" has open PRs — rejected.`);
    return;
  }

  // Delete the branch
  try {
    await github.rest.git.deleteRef({
      owner: context.repo.owner,
      repo: context.repo.repo,
      ref: `heads/${branchName}`,
    });
    console.log(`✓ Deleted branch: ${branchName}`);
  } catch (error) {
    let errorMsg = `❌ **Failed to delete** \`${branchName}\``;
    if (error.status === 404) {
      errorMsg += `\n\nBranch not found — it may have already been deleted.`;
    } else if (error.message?.includes('protected')) {
      errorMsg += `\n\nBranch is protected and cannot be deleted via API.`;
    } else {
      errorMsg += `\n\nError: ${error.message}`;
    }
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: errorMsg,
    });
    console.error(`❌ Failed to delete branch "${branchName}": ${error.message}`);
    return;
  }

  // Check whether any branches from this issue are still alive
  const remainingBranches = [];
  for (const b of issueBranches) {
    if (b === branchName) continue;
    try {
      await github.rest.git.getRef({
        owner: context.repo.owner,
        repo: context.repo.repo,
        ref: `heads/${b}`,
      });
      remainingBranches.push(b);
    } catch (err) {
      if (err.status !== 404) throw err;
      // already gone — treated as resolved
    }
  }

  if (remainingBranches.length > 0) {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: [
        `✅ **Branch deleted** \`${branchName}\``,
        '',
        `The following branch${remainingBranches.length > 1 ? 'es' : ''} in this issue still need attention:`,
        ...remainingBranches.map((b) => `- \`${b}\``),
        '',
        `_Deleted by @${commenter} via IssueOps_`,
      ].join('\n'),
    });
    console.log(`Issue #${issue.number} kept open — ${remainingBranches.length} branch(es) still listed.`);
  } else {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: [
        `✅ **Branch deleted** \`${branchName}\``,
        '',
        'All branches listed in this issue have been resolved. Closing automatically.',
        '',
        `_Deleted by @${commenter} via IssueOps_`,
      ].join('\n'),
    });
    await github.rest.issues.update({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      state: 'closed',
      state_reason: 'completed',
    });
    console.log(`✓ Issue #${issue.number} closed — no remaining branches.`);
  }
}

async function handleIssueOpsCommand({ github, context, core, inputs, repoVars }) {
  const payload = context.payload;
  const issue = payload.issue;
  const comment = payload.comment;

  // Skip PR comments — issue_comment fires for both issues and PRs
  if (issue.pull_request) {
    return;
  }

  // Only act on stale-branch issues
  const labels = (issue.labels || []).map((l) => l.name);
  if (!labels.includes('stale-branch')) {
    return;
  }

  const commentBody = comment.body.trim();
  const commenter = comment.user.login;

  // Parse /delete-branch command
  const deleteMatch = commentBody.match(/^\/delete-branch\s+(\S+)$/i);

  if (!deleteMatch) {
    return;
  }

  // ── Build allowed users: issue assignees + configured watchers ──
  const assigneeLogins = (issue.assignees || []).map((a) => a.login);
  const watchers = parseCsv(repoVars.watchers || inputs.watchers);
  const allowedUsers = new Set([...assigneeLogins, ...watchers]);

  // ── Build policy-protected branches: default branch + excluded_branches ──
  const defaultBranch = context.payload.repository?.default_branch || 'main';
  const excludedBranches = new Set([
    defaultBranch,
    ...parseCsv(repoVars.excludedBranches || inputs.excludedBranches),
  ]);

  console.log(`Commenter: @${commenter}`);
  console.log(`Allowed users (assignees + watchers): [${Array.from(allowedUsers).join(', ')}]`);
  console.log(`Policy-protected branches: [${Array.from(excludedBranches).join(', ')}]`);

  // ── Permission check: allowed user OR write/maintain/admin collaborator ──
  let hasRepoWriteAccess = false;
  try {
    const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
      owner: context.repo.owner,
      repo: context.repo.repo,
      username: commenter,
    });
    hasRepoWriteAccess = ['admin', 'maintain', 'write'].includes(data.permission);
    console.log(`Permission level for @${commenter}: ${data.permission}`);
  } catch (error) {
    if (error.status !== 404) {
      throw error;
    }
    console.warn(`⚠️ @${commenter} is not a collaborator.`);
  }

  if (!allowedUsers.has(commenter) && !hasRepoWriteAccess) {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: `❌ **Permission denied** @${commenter}. Allowed users are the issue assignee, configured watchers, or collaborators with write/maintain/admin access.`,
    });
    console.warn(`⚠️ @${commenter} does not have permission — command rejected.`);
    return;
  }

  // ── Dispatch ──
  await executeDeleteCommand({
    github,
    context,
    issue,
    commenter,
    branchName: deleteMatch[1],
    defaultBranch,
    excludedBranches,
  });

  core.setOutput('stale_count', '0');
  core.setOutput('issues_count', '0');
  core.setOutput('auto_closed_count', '0');
}

async function reconcileIssues({ github, context, dryRun, currentDisplayNames, openStaleIssues }) {
  let autoClosedCount = 0;

  for (const issue of openStaleIssues) {
    if (!issue.title.startsWith('[Stale Branch] Action needed:')) {
      continue;
    }

    const match = issue.title.match(/^\[Stale Branch\] Action needed: .* — (.+)$/);
    if (!match) {
      continue;
    }

    const issueDisplayName = match[1].trim();
    if (currentDisplayNames.has(issueDisplayName)) {
      continue;
    }

    if (dryRun) {
      console.log(`[DRY RUN] Would auto-close issue #${issue.number} (${issue.title})`);
      continue;
    }

    const closeComment = [
      '✅ **Auto-closed by Stale Branch Notifier**',
      '',
      'No actionable stale branches remain for this issue owner in the current scan.',
      '',
      'This usually means all previously listed branches were either:',
      '- deleted',
      '- excluded by policy (`STALE_BRANCH_NOTIFIER_EXCLUDED_BRANCHES` or default branch guard), or',
      '- no longer stale (new activity detected).',
      '',
      'If needed, remove branch exclusions and rerun the action.',
    ].join('\n');

    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      body: closeComment,
    });

    await github.rest.issues.update({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
      state: 'closed',
      state_reason: 'completed',
    });

    autoClosedCount += 1;
    console.log(`✓ Auto-closed stale issue #${issue.number} (${issueDisplayName}) — no actionable stale branches remain.`);
  }

  return autoClosedCount;
}

module.exports = async function runNotifier({ github, context, core, inputs, repoVars = {} }) {
  if (context.eventName === 'issue_comment') {
    return handleIssueOpsCommand({ github, context, core, inputs, repoVars });
  }

  await ensureLabel({ github, context });

  const rawDaysInactive = repoVars.daysInactive || inputs.daysInactive || '15';
  let daysInactive = parseInt(rawDaysInactive, 10);
  if (!Number.isFinite(daysInactive) || daysInactive <= 0) {
    console.warn(`⚠️ Invalid days threshold "${rawDaysInactive}". Falling back to 15 days.`);
    daysInactive = 15;
  }

  const dryRun = String(inputs.dryRun).toLowerCase() === 'true';
  const defaultBranch = context.payload.repository?.default_branch || 'main';
  const watchers = parseCsv(repoVars.watchers || inputs.watchers);
  const excludedBranches = new Set([defaultBranch, ...parseCsv(repoVars.excludedBranches || inputs.excludedBranches)]);
  const watcherMentions = watchers.length > 0 ? watchers.map((watcher) => `@${watcher}`).join(' ') : '(no watchers configured)';

  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - daysInactive);

  console.log(`Config → days_inactive=${daysInactive}, dry_run=${dryRun}`);
  console.log(repoVars.daysInactive ? `✓ Using days threshold from repo variable: ${daysInactive}` : `✓ Using days threshold from action input/default: ${daysInactive}`);
  if (watchers.length > 0) {
    console.log(`${repoVars.watchers ? '✓ Using watchers from repo variable' : '✓ Using watchers from action input'}: [${watchers.join(', ')}]`);
  } else {
    console.log('⚠️ No watchers configured.');
  }
  console.log(`Default branch (always excluded): ${defaultBranch}`);
  console.log(`Excluded branches: [${Array.from(excludedBranches).join(', ')}]`);
  console.log(`Stale cutoff date: ${cutoff.toISOString().split('T')[0]}`);

  const staleBranches = await getStaleBranches({ github, context, cutoff, excludedBranches, defaultBranch });
  console.log(`Stale branches (inactive ${daysInactive}+ days): ${staleBranches.length}`);
  if (staleBranches.length === 0) {
    console.log('✅ No stale branches detected in this run. Will reconcile open stale issues.');
  }

  const byAuthor = {};
  for (const branch of staleBranches) {
    const key = branch.authorLogin ?? branch.authorName;
    if (!byAuthor[key]) {
      byAuthor[key] = {
        login: branch.authorLogin,
        name: branch.authorName,
        email: branch.authorEmail,
        branches: [],
      };
    }
    byAuthor[key].branches.push(branch);
  }

  const currentDisplayNames = new Set(Object.values(byAuthor).map((author) => author.login ?? author.name));
  const openStaleIssues = await github.paginate(github.rest.issues.listForRepo, {
    owner: context.repo.owner,
    repo: context.repo.repo,
    state: 'open',
    labels: 'stale-branch',
    per_page: 100,
  });

  let touchedIssuesCount = 0;
  for (const [key, author] of Object.entries(byAuthor)) {
    const displayName = author.login ?? author.name;
    const mention = author.login ? `@${author.login}` : `**${author.name}**`;

    for (const branch of author.branches) {
      branch.openPrs = await getOpenPrsForBranch({ github, context, branchName: branch.name });
    }

    try {
      const { validLogin, authorInfo } = await resolveAssignableLogin({
        github,
        context,
        dryRun,
        login: author.login,
        name: author.name,
        email: author.email,
      });

      const { touchedIssue } = await createOrUpdateIssue({
        github,
        context,
        dryRun,
        displayName,
        mention,
        branches: author.branches,
        daysInactive,
        defaultBranch,
        watcherMentions,
        validLogin,
        authorInfo,
        watchers,
        openStaleIssues,
      });

      if (touchedIssue) {
        touchedIssuesCount += 1;
      }
    } catch (error) {
      console.error(`❌ Error processing author "${key}": ${error.message}`);
    }
  }

  const autoClosedCount = await reconcileIssues({
    github,
    context,
    dryRun,
    currentDisplayNames,
    openStaleIssues,
  });

  core.setOutput('stale_count', String(staleBranches.length));
  core.setOutput('issues_count', String(touchedIssuesCount));
  core.setOutput('auto_closed_count', String(autoClosedCount));
  console.log(`Done. Processed ${Object.keys(byAuthor).length} author(s), ${staleBranches.length} stale branch(es), auto-closed ${autoClosedCount} issue(s).`);
};